# **tensor-flow** code practice

What is tensorflow?
*   End to end platform for machine learning
*   write fast deep learning code in python
able to access many 





what is tensor?
* Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors.

In [1]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
# creating tensor with tf.constant()   --------> Creates a constant tensor from a tensor-like object.
scalar =tf.constant(7)       # cntrl+shift+ space to get info of variable before 7
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check n-dimensions of tensor
scalar.ndim

0

In [ ]:
# create a vector
vector=tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
# create a matrix
matrix=tf.constant([[10,7],
 [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

by sefault dtype comes with int32 format to change we need to introduce dtype

In [ ]:
# another matrix with specific dtype
another_matrix=tf.constant([[10.,7.],
                            [1.,2.],
                            [5.,6.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 1.,  2.],
       [ 5.,  6.]], dtype=float16)>

#### float16 will take less space to store as compared to int32 in system

In [ ]:
another_matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[10.,7.,8.],
                            [1.,2.,9.],
                            [5.,6.,9]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  8.],
       [ 1.,  2.,  9.],
       [ 5.,  6.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# let's craete a tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                     [1,2,3]],
                    [[1,2,3],
                     [4,5,6]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# what we have created:
* Scalar :a  single number
* vector : a number with direction (eg wind speed )
* matrix :two dimensional array of numbers
* tensor : n-dimensional arrayof number (where n can be from 0 to n)


# create tensor with `tf.variable`

A variable maintains shared, persistent state manipulated by a program.

The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. This initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

In [ ]:
# create same tensor with tf.variable
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try to change one of the elements of changable tensor
changable_tensor[0]
changable_tensor[0]=7
changable_tensor

TypeError: ignored

In [ ]:
# lets try .assign() method to change value in tensor
changable_tensor[0].assign(7)                         # previous value 10 changed to 7 by this method
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# lets try change unchangable tensor
unchangable_tensor[0]=7
unchangable_tensor

TypeError: ignored

In [ ]:
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: ignored

### we can change value of variable tensor where as we can not change values of constant tensor

**Creating Random tensor**

Random tensors are tensors of some abitary size which cointain random numbers.

In [ ]:
# create two random but same tensors
random_1=tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
# are they equal?
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# shuffle order of elements in tensor.

why we need shuffleing the tensor?
* to avoid the overfitting problem or to avoid the training shifting only to one object rather than all objects
* neural network shall train such that it will try to recognise all classes.

In [ ]:
# tf.random.normal -----> normal distrubution
# tf.random.uniform -----> uniform distribution

In [ ]:
#  shuffle a tensor (valuable for  when you want to shuffle a data so the inherant order doesn't effect learning)
not_shuffled=tf.constant([[10,7],
                         [3,4],
                         [2,5]])
# not_shuffled
# shuffle our not shuffled tensor
tf.random.shuffle(not_shuffled)             # Randomly shuffles a tensor along its first dimension.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)                  # when seed is set through this method then the tensor will not change/shuffle
tf.random.shuffle(not_shuffled,seed=42)   

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
#exercise
x1=tf.constant([[4,5],
                [5,6],
                [9,8]])
x1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 6],
       [9, 8]], dtype=int32)>

In [ ]:
tf.random.set_seed(32)    # global level random seed
tf.random.shuffle(x1,seed=32)   # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 8],
       [5, 6],
       [4, 5]], dtype=int32)>

* If we want our shuffled tensor in same order, we need to use global leval seed.
> Rule 4: If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Other ways to make tensors

In [ ]:
# Create tensors of one (1) similar to numpy.ones()
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# crate a tensor of zeros 
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Convert Numpy arrays to tensors
The main difference between Numoy arrays and tensorflow tensors is that tensors can be run on GPU computing

In [ ]:
# turn numpy into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create numpy array in range 1 to 25
numpy_A

#x=tf.constant(some_matrix)     # capital for matrix or tensor
#y=tf.constant(vector)          # non-capital for tensor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A=tf.constant(numpy_A,shape=(3,2,4))
A

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors



1. shape  = **tf.shape**
2. rank =    **tf.ndim**
3. Axis or dimension =   **tensor[0],tensor[:,1] , etc**
4. size    =   **tf.size(tensor)**

In [ ]:
# create a rank 4 tensor    4 dimensions
tensor4=tf.constant(np.arange(0,16),shape=(2,2,2,2))
tensor4.ndim

4

In [ ]:
rank4tensor=tf.ones(shape=(2,3,4,5))
rank4tensor,rank4tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],
 
 
        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]], dtype=float32)>,
 4)

In [ ]:
np.zeros(shape=(2,2,2,2)).ndim

NameError: ignored

In [ ]:
rank4tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
rank4tensor.shape,rank4tensor.ndim,tf.size(rank4tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2*3*4*5     # size 

120

In [ ]:
# get various attributes of our tensor
print("Data type of every element :",rank4tensor.dtype)
print("number of dimensions of tensor (rank) :",rank4tensor.ndim)
print("Shape of a tensor :",rank4tensor.shape)
print("Element along 0 axis :",rank4tensor.shape[0])
print("Element along last axis :",rank4tensor.shape[-1])
print("Total number of elements in our tensor :",tf.size(rank4tensor))
print("Total number of elements in our tensor :",tf.size(rank4tensor).numpy())

Data type of every element : <dtype: 'float32'>
number of dimensions of tensor (rank) : 4
Shape of a tensor : (2, 3, 4, 5)
Element along 0 axis : 2
Element along last axis : 5
Total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor : 120


> INDEXING AND EXPANDING TENSORS

Tensors can be indexed just like python list

In [ ]:
list1=[1,2,3,4]
list1[:2]

[1, 2]

In [ ]:
# get the first 2 elements of each dimension
rank4tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
list1[:1]

[1]

In [ ]:
# get the first element from each dimension from each index except for the final one
rank4tensor[:1,:1,:1,]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank4tensor[:1,:1,:1,:]         # shape=(1, 1, 1, 5)    use of slicing

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank4tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank4tensor[:1,:1,:,:1]     #shape=(1, 1, 4, 1)

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [ ]:
rank4tensor[:1,:,:1,:1]         # shape=(1, 3, 1, 1)

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[1.]],

        [[1.]]]], dtype=float32)>

In [ ]:
rank4tensor[:,:1,:1,:1]         #shape=(2, 1, 1, 1)

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[1.]]],


       [[[1.]]]], dtype=float32)>

In [ ]:
# create rank 2 tensor
import numpy as np

In [ ]:
rank_2_tensor=tf.constant(np.arange(1,5),shape=(2,2))
rank_2_tensor,rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4]])>,
 2)

In [ ]:
# get last item of each row of our rank 2 tensor

In [ ]:
rank_2_tensor[:,-1]       # last 2 items are a column number where we use slicing

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 4])>

Add extra dimension to our rank 2 tensor

In [ ]:
rank_3_tensor=rank_2_tensor[...,tf.newaxis]         # tf.newaxis is `None` as in NumPy.
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [ ]:
rank_3_tensor=rank_2_tensor[:,:,tf.newaxis]        # ... works same way as :,: works
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)       # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=0)    #expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[1, 2],
        [3, 4]]])>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)    #expand the 1-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int64, numpy=
array([[[1, 2]],

       [[3, 4]]])>

# Manupulating tensors (tensors operations)

**Basic operations**
`+` `-` `/` `*`

In [ ]:
# we can add values to a tensor using the addition operator

In [ ]:
tensor=tf.constant([[10,7],
                    [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# oroginal tensor is unchanged even we are performing the basic operations
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use tensorflow built-in functions also for these operations
tf.multiply(tensor,10)          # tensorflow bulit operators speed up the operations when compared to basic operators

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

# **Matrix manipulation**

In machine learning ,matrix manupulation is one of the most common tensor operations.

There are two rules our tensors (or matirx) need to fulfil if we're going to matix multiply them:
1. The inner dimension must match. ----> matrix1=(3X3) matrix2=(3X2) matching inner 3
2. The resulting matirx has the shape of the outer dimensions. matrix1=(3X3) matrix2=(3X2) ------> Reuslt matrix=(3X2)

http://matrixmultiplication.xyz/ # for matrix multiplication

In [ ]:
# The "Dot Product" is where we multiply matching members, then sum up  (matix multiplication is actually a dot product)

In [ ]:
# Matrix multiplication in tensorflow   t(f.linalg.matmul)--------> gives dot product

In [ ]:
print("Original tensor :",tensor)
# tf.linalg.matmul(tensor,tensor)
print("Multiplication of 2 tensor using matmul :",tf.matmul(tensor,tensor))

Original tensor : tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
Multiplication of 2 tensor using matmul : tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [ ]:
print("Original tensor :",tensor)
print("-"*90)
print("basic multiplication of two tensor :",tensor*tensor)
print("-"*90)
print("Multiplication of 2 tensor using matmul DOT Product :",tf.matmul(tensor,tensor))

Original tensor : tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
------------------------------------------------------------------------------------------
basic multiplication of two tensor : tf.Tensor(
[[100  49]
 [  9  16]], shape=(2, 2), dtype=int32)
------------------------------------------------------------------------------------------
Multiplication of 2 tensor using matmul DOT Product : tf.Tensor(
[[121  98]
 [ 42  37]], shape=(2, 2), dtype=int32)


In [ ]:
t1=tf.constant([[1,2,5],
                [7,2,1],
               [3,3,3]])
t2=tf.constant([[3,5],
                [6,7],
                [1,8]])
tf.matmul(t1,t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# matrix multiplication with python operator "@"
t1 @ t2             # @ operator works similar to tf.multmul function 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# create a tensor (3,2) shape
x=tf.constant([[1,2],
              [3,4],
              [5,6]])
# create another matrix with (3,2) shape
y=tf.constant([[7,8],
               [9,10],
               [11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
x @ y       # dont work for different shape other than ((2,2),(3,3),...)

InvalidArgumentError: ignored

In [ ]:
tf.matmul(x,y)       # dont work for different shape other than ((2,2),(3,3),...)

InvalidArgumentError: ignored

In [ ]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# let's change shape of y
tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
x.shape,tf.reshape(y,shape=(2,3)).shape              # inner dimensions are 2 so they can multiply eachother 

(TensorShape([3, 2]), TensorShape([2, 3]))

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# changing shape of x
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
tf.reshape(x,shape=(2,3)) @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# can we we do the same with transpose?
print("Original tensor",x)
print("-"*90)
print("Transposed tensor",tf.transpose(x))
print("-"*90)
print("Reshaped tensor",tf.reshape(x,shape=(2,3)))

Original tensor tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
------------------------------------------------------------------------------------------
Transposed tensor tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)
------------------------------------------------------------------------------------------
Reshaped tensor tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


`The new matrix obtained by interchanging the rows and columns of the original matrix is called as the transpose of the matrix`

## try matrix multiplication with transpose

In [ ]:
x @ tf.transpose(y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

transpose flips axis where as reshape shuffles the elements in tensor

**DOT product**

Matrix multiplication is also reffered as dot product.

we can perform matrix multiplication using:
* `tf.matmul()`
*`tf.tensordot()`
* `@`

* Transposing results in different output than reshaping

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

when performing matrix multiplication on two tensors and one of the axes dosent line up we will transpose one of the tensor rather than reshape to satisfy matrix multiplication rules. 

In [ ]:
# changing the data type of tensor

In [ ]:
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# https://www.tensorflow.org/guide/mixed_precision

Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory. By keeping certain parts of the model in the 32-bit types for numeric stability, the model will have a lower step time and train equally as well in terms of the evaluation metrics such as accuracy.

In [ ]:
# change from float32 to float16 (reduced precision)
D=tf.cast(B,dtype=tf.float16)             # tf.cast is used here
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# change fromin32 to float16
E=tf.constant([2,3])
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 tf.int32)

In [ ]:
E_float16=tf.cast(E,dtype=tf.float16)
E_float16,E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2., 3.], dtype=float16)>,
 tf.float16)

### Aggregating tensors

Aggregating tensors = condensing tem multiple values down to a smaller amount of values.

In [ ]:
# get absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# To get absolute values 
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregations:
* get the minimum
* get the maximum
* get the mean of tensor
* get the sum of tensor

In [ ]:
import numpy as np
A=tf.constant(np.random.randint(0,100,size=50))
A

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([59, 57, 34, 60, 24,  1, 16, 47,  6, 26,  0, 17,  7, 19, 31, 62, 78,
       27, 23, 58, 60, 15, 71, 91, 82, 91, 46, 66,  7,  6, 64, 44, 53, 26,
       52, 16, 77, 94, 54, 41, 83,  2, 40, 94, 56, 65, 24, 64, 80, 77])>

In [ ]:
tf.size(A),A.shape,A.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# find the minimum 
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# find the maximum
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int64, numpy=94>

In [ ]:
# find the mean
tf.reduce_mean(A)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
# find the sum
tf.reduce_sum(A)

<tf.Tensor: shape=(), dtype=int64, numpy=2293>

In [ ]:
# find the variance
tf.reduce_variance(A)

TypeError: ignored

In [ ]:
# To find out standard daviation
tf.reduce_std(A)

AttributeError: ignored

In [ ]:
import tensorflow_probability as tfp # we need access to find variance and std

In [ ]:
tfp.stats.variance(A)

<tf.Tensor: shape=(), dtype=int64, numpy=771>

In [ ]:
# find the standard daviation
tf.math.reduce_std(A)

TypeError: ignored

In [ ]:
# we need to convert it to float values using cast method
tf.math.reduce_std(tf.cast(A,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.77>

In [ ]:
# find the variance of A tensor without tfp
tf.math.reduce_variance(tf.cast(A,dtype=tf.float16))    # we can use this method also for calculating the variance

<tf.Tensor: shape=(), dtype=float16, numpy=771.0>

### find the positional maximum and minimim



In [ ]:
# create new tensor to find positional maximum and minimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

Squeezing the tensor (removing all single dimensions)

In [3]:
# create a tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [4]:
# in squezzing we nned to look for shape 
G.shape

TensorShape([1, 1, 1, 1, 50])

In [5]:
G_squeeze=tf.squeeze(G)
G_squeeze,G_squeeze.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

In [6]:
# squeeze reduces the dimensions of one if there are multiple dimensions ina tensor

### one hot encoaded tensor

* onehot encoading is a form of numeric encoading

In [8]:
# create a list of indices
some_list=[0,1,2,3]

# onehot  encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [9]:
# specify custom values for one hot encoading
tf.one_hot(some_list,depth=4,on_value='bhagyashri',off_value='prashant')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'bhagyashri', b'prashant', b'prashant', b'prashant'],
       [b'prashant', b'bhagyashri', b'prashant', b'prashant'],
       [b'prashant', b'prashant', b'bhagyashri', b'prashant'],
       [b'prashant', b'prashant', b'prashant', b'bhagyashri']],
      dtype=object)>

### squaring log square root

In [10]:
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [11]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [12]:
# find square root
tf.sqrt(H)

InvalidArgumentError: ignored

In [13]:
# find square root
tf.sqrt(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [14]:
# find log
tf.log(H)

AttributeError: ignored

In [16]:
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### tensor and NUMPY

Tensorflow interacts beautifully with numpy arrays

In [18]:
# create a tensor directly from a numpy array
import numpy as np
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [19]:
# convert tensor back to tensor
np.array(J)

array([ 3.,  7., 10.])

In [21]:
J.numpy()

array([ 3.,  7., 10.])

In [22]:
# the deafault type of each are slightly different
numpy_j=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10.])
numpy_j.dtype,tensor_j.dtype

(tf.float64, tf.float32)

# TO check GPU running ?

In [25]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [26]:
tf.config.list_physical_devices('GPU')

[]

In [27]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found
